import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-mode-toggle-button";
import Profile from "@/components/Profile";
import NavigationDrawer from "@/components/NavigationDrawer";
import "@radix-ui/themes/styles.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { AuthContextProvider } from "./context/AuthContext";
import Image from "next/image";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Visual Lab",
  description: "Generated by create next app",
  // icons:{
  //   icon: "/favicon.ico",
  // },
  };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Head>
        <link rel="icon" href="/favicon.ico" sizes="16x16" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head> */}
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthContextProvider>
          <nav className="w-full bg-background text-foreground h-16 flex items-center justify-between p-2 sticky top-0 z-30">
            <NavigationDrawer />
            <div className="text-xl font-normal flex">
              {/* <img src="src\app\logo-removebg-preview.png" width={40} height={40} /> */}
              <Link href={"/"}>Visual Lab</Link>
            </div>
            
            <div className="flex  justify-between items-center">
              <ModeToggle />
              <Profile />
            </div>
          </nav>
          {children}
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
