import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-mode-toggle-button";
import { AvatarIcon } from "@radix-ui/react-icons";
import Profile from "@/components/Profile";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Visual Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="w-full p-4 flex justify-between items-center">
            <div className="logo  p-2 text-2xl">Visual Lab</div>
            <div className=" w-2/3 flex opacity-55 justify-start gap-2 p-2 text-lg">
              <a href="">DSA</a>
              <a href="">TextEditor</a>
            </div>
            <div className="flex  justify-between items-center w-20">
              <ModeToggle />
              <Profile/>
            </div>
          </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
